{application,controller_app,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{controller_app_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[controller,controller_app_app,controller_app_sup,
                        lib_appl,lib_vm]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
